# Generated by Django 2.2.6 on 2019-12-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
